# Generated by Django 5.1 on 2024-08-24 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(db_index=True)),
                ('event_name', models.CharField(max_length=255)),
                ('event_description', models.TextField()),
                ('tags', models.CharField(max_length=255)),
                ('additional_info_link', models.URLField()),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WikipediaEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('page_title', models.CharField(max_length=255)),
                ('solar_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wikipedia_edits', to='events.event')),
            ],
        ),
    ]
