# Generated by Django 5.1 on 2024-08-24 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='processed',
        ),
        migrations.RemoveField(
            model_name='event',
            name='processed_at',
        ),
        migrations.AlterField(
            model_name='event',
            name='additional_info_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='WikipediaArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='WikipediaChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('user', models.CharField(max_length=255)),
                ('comment', models.TextField()),
                ('matched_content', models.TextField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='events.event')),
            ],
        ),
        migrations.DeleteModel(
            name='WikipediaEdit',
        ),
    ]
